apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8-golang-demo.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "k8-golang-demo.labels" . | nindent 4 }}
type: Opaque
data:
  mysqlPassword: {{ .Values.mysql.mysqlPassword | b64enc | quote }}