apiVersion: v2
name: k8-golang-demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: mysql
    version: 8.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    alias: mysql
